name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: npm

      - name: Update npm
        run: npm install -g npm@latest

      - name: Dump version
        run: |
          node -v
          npm --version

      - name: Install dependencies
        run: npm ci

      # - name: Test build
      #   env:
      #     INPUT_TOKEN: ${{ secrets.TOKEN }}
      #   run: npm run all

  # create-gist:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Test action
  #       id: deploy-gist
  #       uses: ./
  #       with:
  #         token: ${{ secrets.TOKEN }}
  #         file_path: ./__tests__/foo.bar

  #     - name: Dump action output
  #       run: echo "${{ steps.deploy-gist.outputs.gist_id }}"

  with-all-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Test action
        uses: ./
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: c53238c34fb3325526790acbbb6b3a98
          gist_description: "foo bar"
          gist_file_name: foo.bar
          file_path: ./__tests__/foo.bar
          file_type: text

  with-binary-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Test action
        uses: ./
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: c53238c34fb3325526790acbbb6b3a98
          file_path: ./__tests__/dummy.pdf
          file_type: binary
